blank_issues_enabled: false
contact_links:
  - name: 🦆 skUnity Discord
    url: https://discord.gg/skript
    about: For general help with SkBee join skUnity's Discord
  - name: 🚰 SpigotMC Resource
    url: https://www.spigotmc.org/resources/skbee-skript-addon.75839/
    about: Read about SkBee!
